[package]
name = "rust_sample_bin"
version = "0.1.0"
authors = ["Hideaki Igarashi <hide+github@5stm.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
